---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-internal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Virgil-Bulens/homelab
    targetRevision: HEAD
    path: infrastructure/external-dns-internal
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
