---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    client_id: AgA6wXal5c+2qcs+e52hjR51/b8ga/Ayh+9WaCuruc2N9gg9W3bjZaTNVwi1i8v+zeX38NDGjIRbaKheXbHrv4m0OXwHzmWy0Eb7VV8UfOjiz3kHC33TTZhpbynxnwNrFYobBq11Pz3UV6r9sN1OeKVdCWg9+V85DR65diWWCEWfPReyH7vM3hnPIyBwI98SVazdMVA97hDPgKlbCoqQVpnkb6OAgI4dLCdP08pxd6NYjd5lePcMfyJ0y3zrwvwkCQjyoZls4FOtIQEhj0J5EHvgmWt5iEbNrNEgwRlqUOCrOxqNIUqEBmnGo0FfwQJd2D3CUazIogwjYmNyQAmjyoOFDPpo71jYzeEnCRKpHAp+LVITgIn2KPQ+NkowLf/8xVHoFMhLg2LH3WM9HrhwKRlSCyd7sMevQO16OJ9OFf9r5lPMK9EbrDFdZJqick6EBr9atMXb1uYP1Dl6tx+mv5eGzjIUbFtPxnpcuObWWnZSGuoQi+g4bkHlKeDVQuApgqgxgNBvzEDtrpDIvy43Ridvv1HIs0KysB5mY5oQ5WLmnOJ5iMcC5S7W0DoRQ8TYN31r2ADmHVFfGdPW5ttHZ8ATvgVJ9h44h6Why7cvnbqxvR401E0kDafEEF62Cg5bxuYxk7Uf5r2W2/yLXui98fsbJrGuDLxuMthUWQoBXTfvpuxUzgd7eUXjV/C3FrE9YTlMm1gME6tjpM6RMVcq1xCpPjHZqE3POZgWDxIsBCJ57gXRDwo=
    client_secret: AgDPFv4sTiVfnhxoo6bmDdwAOAwTAmLyk3ke0S9QZJP0BILm9FShInn/YykshOcwGf6J9sjiyTpI8Ft0FwdzvcYaAAHAvnvHeKpH1LY8YNzBuWUuuU5qljeDmKrb72lGCX8NePKNPTQLkOTq3MJjJCyD2gQZ4RHHb5QIOF40C11RNI9Kxuy5E8plewcvIwxW413ESyM18uIEuHPbmehzZ6qsjXaRfDEUmdagB1dDC71/e/gCYWLhAEceHE28530FwZL8e/kh9CPEeNpWSNrVOBiAKSdmQweMsfZ87DonyfNa7kDhTmhrnYBF7q5Vfw8SFlgKk0Ko+l899R9QMufxj0T3D7pxS0sEZ74se9lBS68MMqjTuBl0VBV2dzaYmzqpVbwdQiZ1nEnK98w1MsG6DlFdpvYoixPBzKLtMGu/X4wyl+sAKyYZ/mjF/2HgdghGdNRoqsiDZdI/m1KztJxecWax9otd3TiRg+wvWk4showi1F21CHzvunWgEUVc6n9/FbeNUoYaSB6wFa2YQ2LB+LUTOSc7ljwjCNd9sQgPzx9uKd/GAfC4XBnroOYMa8YQMd9HtrIJAK8pRcZV2HmlMDQJE7euueF8zM1T2wA1p1jB7FUc9RMI5Zyo28e7EaEdVvz3dEhFZycTd6hT8/aU8BLdyvsBppCG6h9YwpuQuoCvVFhrtH1QjyFZA3QRrKLLEdUKhlpOqKxYdpFaXYorHq87e5rtnyfQNXX0MqQwDo/zJq8ubpTQ5550YPuFksA4RuiWVIDHQlNNdPIobBCgJrBYZH74lfxWhkwT8JXLMEu+pbfuPY7YX1BBkP0lYI3xMmQh2y1ZEcChHrd3PP0c9UFTSjDaE7Aj+QM2Fq+fLt5wjw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd
    type: Opaque
