---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    client_id: AgA0htH+WbINJEPv3PV8ouHB7TdGiCy/zS+S3JdyMqXj3ae8gawH7rB6FR2By2D2T9ZqWkzCyy7gqDXQsUeVyL9tFaHA5hCVPYvIJEQSi28W03BothLiBU45DR9S0w9sjw9Gr6xxV6SYbp7SKBa+xXryAJxyfwQVbMohsU5qLjyN2RS9YfxjaiowhhSX5p/Awd6EcFH3ESGz6o0fJA7lMbxoGFV5rEMvc+NE7PYJ/gCsvW4TT/WJCwQy/1T/FDuA4nOViebXJnX/0eO/EASpNbco66VUCE/SA3L7X8BVaWTdQlWo4bnFaS19uSynI28JsQl8I2Gb6/MVsp9JYO5aA5QIsolzXsy46qNBxT//hxFsOw5D5DM+PCnb0W/i/7PeKDMUeJsiXaUqJYOoUmgaeubcwWVQVlG9fX9y/XXAcW4dRdJqcDN2fZsjpWksoF1TTdXW1ZOPsELRPmO0JGi79P1bkk7dTBE92fbnegtRXKp4Tkd7MbLXtChjdM7xJW5YGRYUxhxyozRUVw37O2O3ZcJ147qo1MPz4TsPzBXPlH/pWnMhmNl0CJTHpokYcTiufvJE/1VeBhkVpEV5E5HM8rD2kJ1M+BWoRCsYXRWQCZU3YGLm+RKviKEkWHDH+ACZsnC6houC9JtM9GsZmHQ5E2c6ds/Z68ESsvbrAb1H9hFIkD5Ixv4VEqgTMcoG8QAM3PsnXnkL7B1bZXjU3U/imV8CgEan1xA2bsDakDIJbnYTBqEIKZI=
    client_secret: AgDOwcAXUBWEUeKQYOIKS6f9ItymWL4J8nQVcL80kwM5iXPz0VPHNZ4GmfVwu0sEU3O41eaoJN/zc+/bogvijne/zujLguM9TRIsKKO8xmoV+O9rtbf//UdRgAB+h87iV7OfBUoYy6KDCLk6+04io5KZ1Nb9ymfXVe59g8eerqnvYRXih5RewnJLFReeduVdMod/Mpuhq3OoNEvv3eWvOuEXpSf/9ShE45ZisjVj6o+MyPtrX3nUVvjgCmVxgVg8BUps+Ydh+Na5N9/1LCQ5v5UgnUtJSR0vB8IRbDS45Hfi3aEqsuypf9QG6HcfQC+NAOKpY4DEzlaSS/7xLC4jTTGBEQFqqEUN68RZQc/d62m3hpmd04qqolbvKd/OPfB3C2wXFTteKtJM358Pky8LDdgZIi8RiTMaevV8zVzsjSY7jgJ9vl13y5BwR1vIDmrQ+AnoBp5obKUpsd2kkH+XsW8kGlxxN26wiFnSY+6hIJtl7r5zaeh8ZOpqA9qMK2GddthidChzaKr282c5fELYLfMODOmrw43WJEYZ9q2HK8YJgbizIThACjRvRy27UqUeZ3g+LXcjlKaPw2iHLFlgvqW33JW1RcetIA2jqbmzPMjtZlFLBtNLyQp4TirFTSHcihoflzw/rlkxyo3NJddpM/R5H2G4Iy8qq41tjTov+9ne4r02Yzty/Gejp8pNcDhV/Uvz9nABhwf4OTkJnS3/A1gezdgMtU89VxJBHjm1rU+2zgl3HNeku7AR7ujEKkCOePtCusLjpyVOh5kBjjJK1HYe3WXoVYr4TcZEVZkTTL5APvQu0pgBG2smiDWto9TqIaq866QfCsALonXHbDZSQfzS9Ab8UoVyutm3lqDHtvg/GA==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc
      namespace: argocd
    type: Opaque
