---
# Wildcard certificate for *.virg.be — issued via DNS-01 (Cloudflare).
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: virg-be-wildcard
  namespace: networking
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: virg-be-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "virg.be"
    - "*.virg.be"
