---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB1iukdm6aca/C5fWbtzwMXqn6prToNRdCfhbFIo0mpMH4uAkBSaedEJdNLWXgL3ySpOwuK4EJwCkUmeAfQ3iGiu7yLC/E8rdhwSteJ0Nq78w8cZti5eMZn3tkDGqro4RYkLw5RDW3pVHybfH2pWxWm+WliH44YcupCEvmYpWUIZNqubfbUuPq9dMjnPof/PCEpEiTs4YDhDd1Lms6PGLPI1/rQ3oB0OSsQeP8etHMPvaJTbqxTx82WkoJCzeVO+hTRgxis+uHsfy/kzFAh2tLDscoKrAmcNvpgT6waisEpE3freckZtOhVTG4gsa3f2nqP9Xfsh8odqkfYaSRhX+vegRevp92i1zZxFVbz24W5OF0UTU8dokAsZcOUeIWtkf/w7wQU0oSVWbHHzRZ+dX59XkG1MlZqqWna5122bZDBL3EwnBg3+J22Fd++5sUtrzTT4pbGqLr+AUDywce98+j/Qtdtb5LnC0egz/UYj6YrmHpHCAJygAAGUDJU9/8MBCaqMPRZY/ZK1ay2WQrOvuJ06bZGMpQtNiderKJtGG3dYDyTDqOdNfRFF5H8xVjtoRPdjcUEKcdIwCSDB65/upJII8GjRdwf843oqzpIEdvw7cdaHrHufgg0igThdL0B9s8RaLhsFAJHj1gsuHHazbrspK0mQWxmB2eU4K7x/oKv+4ppEmsjDdewg0YvaAJSjOqMCAxPmplXCggS7jc29H/mky5seNmr9GCF9NuhQO1BZg==
    admin-user: AgAa1XzY65y/qls8qHCeYhpwN9DjfP2GJMUi5MaaY85hGlHZvEXHLFU27WIsKi3SGRbxdDq4qFUuP36HCBIVVYc1hX/fsPFV1dGIGZD4fCVaSP6u9f52AbEMek/6V5efKWlcASM4/M7wq+ypNaWQzEt39oBo+Vgd+H7LMd1yPaEXJqxR4bWrg9zG1W+UsIRmP2vYEh4Yl95hU6ysFAZOfVjyF3cSHb3EIx1i7C1H4o30acJic8mztOaepsyZnqIOPeZXvKMSFGrBeBfnkM0AVE2KHrh758m27d0I1LXY/1ZzC343BDTJrSckrH1ppJ9aLPAQC3uOb24JaSOH3a2OeQRAaAKjJpM2z4kIUMEZ8wb+AhKnSbfGc2Kjhh4ydBxxBsrFgQHqWroyyHQ1W5mw3ErbwxJ0YLp9JVvWT++GOZFIY9xpIz4tR10okOJVR869opVWEaj2qXc0BkuRDMjDZdwQb+bIFuIjUaC9FnktntlM2ckKGtn06O8y8YigebyuwrIjR5sZ70e7h9hzhmT+X556Szoz3TNgijGz5p8a3CyX9Dogh8ybiDKC1tNjRhNh6TgvwQKZmvWLA1WaauyL2z/nFPsryr3SjCxPp7cfHAcqrD3Gja69L64TIQKvE0V2Bhz31S3lgzoqrPdtBxjFxb9+qTZuGaHWFwi44+bU1+aatvSJzV6YnQPeU5k0+Po1cP9koHFWUw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
