---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgAqREKXatUQpDtPOhiLxn0InVp6IUSdoGjLb8jPBMhlXFdBy+lOCf8uHnlg/a2Esb9q/FFaY6RfSbBi5l9i7jD0kfkK2o31fVWWkuq24tN9BisPZDy9VidAbJe5d0cr6yO/b+Ggpt/YwDuXColig1plbrMtPH2aBvQePjmxbHdVzHdb9AG89WM8OkH3j6ET3dAJb5aSzoqX8SCTSpUXphOE1+D7zkYff4aMAGk4j3nV4YvUk/Ayb+IcWmb5WJWEwtIFWgdf2WUi5AcAwYlkVxp/k2lukj09iDzfluGKfsaaG1WAXBrMYbzon30zigkdNGWcugX1hEbS6mLFvpuGwS0tffrf2axxhmKn/W7TVkSk1eFxCi6DUCAzGJ3OHcVlhZ7Z4rOv/H4XneiXFABJKNTR0YdVm43vn4DJO7yLhOsIJS8alp866V/LgacTkcQ9SFl3okPczYQorkvUDylwlgcBZ8989didEVX8JIfut9XS/0sB6ss5CkU8a/Z1Frvfg5ADUmOcjvykBCBS/fQbb3NlSJEeWoa8njcNNe/mJH4k2TyZv4aZToX0/58DBam9dndkXzpZbjAWzDADT6q+cpwBV/8NqxFzad21peQvqYKVeZEFuugRyhO93QKsacZFKo2WyAot+y547ZkA9UbiXXy7PA51bxi99K+efwMHIDoC4SSZEhP3p3fRZtEXrpnDQaXf1d3UC4gJYkMWZLXhsZM85lw6UDI91EdrdsPUieySnxlpK98=
    client_secret: AgCGo3Oc37LkemUUsC+l+3hI6cj9qIzsus9cvW0KxCiqbY64F4PRlzW4XJTSyLSwLSPt4/6OMfuw3Nbfo0BxcbGbaIWlHT/1JIEm2Eu9ZAFUG6cS+70hKH4FF7k40pTM3HTDH8iF/Pfj/J6YMi+uye+O2mUYXwn01WL2GmxZl9YTaHm8hLcWYInheLHHqVH8KTl5HoogCHJBcNwRIiIvDb6TDIDCUjurbJBYtuxLat7+69EdtDT9LG7skJXi9pAxGwAV+wofcN5C192/CoMzkwnePLRAQh+D3SS3ay/62N1o1VEwbpfF5KYTfLK8+Z4S2BhAoG4cKn8Z0YOq6zUFsCUj92xWNq/ownPGvcnns5pAg2cesOHgNlO5WDis9Aapuk3+zaOvqz9BXhNjUQGlnoNemSoP9B+Vv9NvKab3+d2CxcSFA9jrNbpUKbQcZlUzdVXNzeWG7b2k5x77qWwmvUILhpZV30PiifJ7WKzO4GdUjK7odWVToLuacc5l+FgXyCYIWjYCvrpdkW091JsN4eGiQmWe39c0D+v/LFtG+Nq69M9VY21sQ86wwuO0mhvJs0thrTtu1mXE8T1p5W0nszHqEMPvqaFdDcuLRYP5quiLYLZCM0vciSJxFYw4btCxzhwBS5qpzDvja1ipLyGdA/Gq0aZ5p1XL9DDCu5v/v6I7mENnKOlgBeeIAQBeRghgytGWlAuUNNqBY6okCh93h6h1ESLbOHzmjjjhuhw5XQbCXbWpYjCaXuEGpR4J/X9BuwnjQ2fzZay4sAnajvQYAUEMuPjr+kNCdsd+ZjSBlBmjP+MnOlwXJJIMnXbsUy/tWBLx1Y19BcIhaLVpuVNamjHwqG1jTiPnxOhMnJMh1ViLTg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc
      namespace: monitoring
    type: Opaque
