---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pve-exporter-secret
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgAxNpF/E6Yssm4fVqh3bsduticHowyObhd3aCW0SQ7XLGCXwKYLCmRY4c7JxnLcCRsTAc8EzTUPIqsDQRwEt0HOhK70t4whata51GdmbdqmK07DEitgo9sw+ezkrFabo+loIuTbeUwiVY7JXRYRNJRPFZqpYpzP5l6dPG42tgzUcMopzs3r7yzRy4QYPL0sUSm0wByptuQjpi+bc9AodcAtsui5BJ2d0uBXyQNktcVhIjirrMW02y35X41t8NAg0CQ8pENffOYLOxVdMqWCJsMOxLDV8nW8mfIw1G/XQOrUNgePPRF0eU50mcEdYtq1KoIWpHUPsVaFVWxChwxEJrFkAKVM5icre18o957vUQoNNsxKggdrU7K+cMbNTmNUW25y4DvKB+9NWTGzcDdy+k5GnghWB5Fg7tuZKeyei7QeEIOKtR+3MvsRIwAy/GhV85U+LFQj4XXYWrBE2nWZI0cPgEd+8Hr9Mb6du0oWuXFnjWqGdoLfIX7P3sFTpp8h5rQgd4hylY3zjA2kez9SzcSGARUh/2WPC9DvAAi1sa9nigwtm5K04wXhekNmp1BGJTuei/uVLbkuZylVpnoD+xPMuBMC1WrGTBiz5De1POyKUJV0IzK2v9Pm7cAPDbwvAFUk44f+JDVcT4i2dak2b3rI7QE6zFEXwM9mcEzTBzjqDQ4tlFp/O57kV/YnuataAz3sbMy/el2r/5vXSo0LY/nVXbUtA4mC/QBtBYm4RsIwN0bdND0qW27axyJvdmtbyV51XjutwgxDkk5HfJ6EMX2JovCEWVCGpLHtzfhp1VZtAnWYy0ZWuZ5NbDy2jYy6aGS0/paAp8Xn1+ZiYd09UKwiKmDgZp8KDkEUODh8VquNkw==
  template:
    metadata:
      creationTimestamp: null
      name: pve-exporter-secret
      namespace: monitoring
