---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifi-poller-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgB8AwYR7tDzO+4mVjEkczZa/cV0qLfFd/76lvUON6DSPM9QwQZ4EcPIg1VqIpy0CfwA553c9Nue7KK9AoLWzs7gcnbIwGYSl3hnupeKBEFzxxL0k7hM1xLUTl4L1dQ1cChIv0d3P9Sn5fe2i2YaLTujB9VCyG2nDE5u0NkCmf15811l609zKZXRYze+u8OUrKva2o3Vu76B6lXRQU0BVj8vRIaTjClPvlvNCiOrU8+gijJ66Bd0JDUZsSSKj4oRupvFmT2RRS4EeTl3t3SFn1oYrvlyP6GL4xkiF7FOpyu9GPh9EhPTKL2copdXXCjtba7wIFDyShNvMMM77w1JPKmIoaQ+ZcQhnoomMVpQ+5alxk5nLPgf07Ybu695QJnpe+TqCY3L7yGoHPczOrfxqwwrFCuYhJbCjGnKPynyhhnK7pjRwV1EWf4xzcCdb8+8CpDgpmU5WImkKucaYD2MLqMTwLtQindlcSTp3hOmp1uVyXd7GTqKtTBezK9NeIv6gKfksesAzxjH+2zqw2fkW8ZSEtGz2p+gm5c3s6QUPpungJbny3UvuM076fH5y5W4KpMeJxyR8v1zuKr0WvjgOKUdT8y4ejMrLqEzzlOynh8P5ulwK/98YIJEgQP6gv1Rb1ICZL3HUSQS/QOKp+fmrc+QxkeRewINI7UfCZhHlMfwCBuHkbFl9CcyLLuKSlcMq9bCoP4fjIobpYnpuj/cshwzY94wNw==
    user: AgCunJja2nLshHaftWa5vbYbrhbe7vSXc3RLqaz1ZmiM1esfrBP++kc1AzhCLvFsMk0htnfkSx2f9CVSlkUxXBM8q7G6CnJQxLwlUHuV4UhcornONqZlENOT3OR7yma0dB/b15P78IEx9RPvS8qRoZTtqf0g4Gvm17uQgyWpadm5lYSyVMOv7mytd6GItmRH6l+1krgzgBLQXR6zOgWdkqo6vOFoa9dtL/bvBgrzYxaFRkF/4x31zs+hZbuSNTL8oBmZCqGDjanU3z0c1PRYlSI0bLNxIxZmMD6f9LbRfDcDOMASRtwO6Ph/KepLNLZeq+5yfNQEw14ntO5iiBDIjmm7mnrlzA8VIWPe4B0tCH5i7rVDyKDKbhqDK7LdDmUe0Wc5M6sMRlcN/nFYwZPvIbBxsHjQVjgtqXs/ABWepRHLHLgWu56Hv7SXjTYfuiqsY8XS8oajMdM5grczGc8cGE4C28yU9TQBEB7Xh7ruOvQuubXcnjbbKdY5RxZ9YDMLiJdB3WHXT7VqpqX94byMXGdaaJPbCbAUY/khhgPA0R2s8R06Pz+4M3UdXWAHs0hNCPKd9MlR8MiC3fz/iFVWO4kmCAK170PMSKEOFjwqbANnY7Z9XS1EIbg1NRYJQ3aGbSixP1vOJ8TnU2ybFVLsCPobV9dFqso2Ad7JGvypVwNx7yiIaaoSeZ4myqqgJTqgkQ4vKo91C8oQ1vG+eAw=
  template:
    metadata:
      creationTimestamp: null
      name: unifi-poller-secret
      namespace: monitoring
