---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifi-poller-secret
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgA6reCyL115XQBvSxz6/iHJeNw6a5LG2LqPEfBAB8dNMKmnkqOdpSuP9oByQdXTtLHTFclNa+7lCJcidL72dgoKStbGRoB508/MNkT48/S9JYNaxYBLFoVmbkmleMsf59cqEiA7BgIqnThK8V8+XJaTNsgzl5XU+Q9htkCRVlVWdyxFlCb7uOmc/3UNIN+H8j82T7C6AxvyRWHAB5sG9n18Rpdv5CNKQo+4QrsBcndYTeD2WZePb+eazI/dKakP8T0bQbR+e39xZU1KAVZOREGsDlUAkWZp9MqEgzOtNU+2/vizxDQdfNy2KW5/Aj87049X5L8DPSAIfMR5Gx1lMTUlmUmxNcmI4ORUgQDq4g3hax8jdXNCE7IytSWJLJlUnrS65yd3HW42Rj1yIjpRSjrmSggM9nBcIluC+WhuIRVajGy3bbPUPWGV4GsJcqTNcMDm2tL1Tf18OnARtsRIdev1aKm8EjwCPB8zAcmx9gWk7v4uKQ+9FAgph+o4RL9TuCF6th4VUr/X14CWEiMEGpWQ1O6emLhJGADFjw4Ity0W1g4PTJiMKr6NgI/XDd+GgGsBPzTT6pfFsEizdQO+McaLQZ0Rg1aKKy4SiaE0n4vQA1TRZEBmUuRKl+KF4u/0B9RYSDPRYRHV6uBO/A4lnnJVGlZKC0wH1dgGhmpAG3D6rMPDUY+Nc05sjEMTdaiyx7PxWbxX5vEz5dVfdkpss+RzTvY1dHRcVoVqg0UKguPA9sIHNEjDEid6IBOTEVfess2Nph8mN8a1kLQSWuUdRrVzsQ7sDw8xw5lvcQ1vF+Q3fMhB9LF7I6rufKbPp0zQ2WHlanl5oSB+NF58RO5ruXQ9MQJZAaCHAuLkSDAsLAKPQXkH0pwurXeC++zpV+qMcg7qp2BipGIoYu87bzcL3qgn2pH/RJ8wDwBOzSucq3RhXtMvrO3TA0Xguu40u7elw39F1VraBleExYvPM7Hz1FEteYyxs7lYsPTcpjMmO+W8LW99zsyjpK87+78uTbwYfp5wAsElvuBrLpBjxxOZsgcJSx/pous5NZclLbhFRcjIPVJrJBOfjeBAMQK083PAxx/oHN9x4Xnp+QbYyQh/girr5uXOytm706g56ePjv4uf0+EmmZgtKQjOYVpmjeflFeuAq1VD2eFvcgwsE25oRd5PcTNKyHsV6Ew1Mlyv89B0N/ilROcuWdkOZXXt4S1EdCFJmYRYbhwKMvL/pV0SjVBY4LFROETRr2SP3AofsBo=
  template:
    metadata:
      creationTimestamp: null
      name: unifi-poller-secret
      namespace: monitoring
