---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifi-poller-secret
  namespace: monitoring
spec:
  encryptedData:
    up.yaml: AgDo+0NB/T1qdtBVaNcq92c7UE/Nu6J87jy1IG0rOZa0ATAWgbXnS5EAmgivmmmZVQUAjlJRz5GL7E+gcJIi2RKhVK82hNzSwGdWfF6XAk1G5MPiCvVkm1x0pDi9piYO26SHmDLK9DFrWroVawIkPNlL3ureTXBmqsIgufk+6Se8HEzcShGJh+6db4ZCXsh4aEsbr/dV+KuNQNGqxvoz8Iu2yySYNQZ7Kc7QP64KtkK+LNcaShGSrpT36o8MfcaKI6sWYgNwJOAIUrF3UqeO+0OS7vEINchrh1RJjL7VYeHB2g0qcEDHV9MSNAK7VacSLFhg0e1ESpitNoTiuiB+zHWdwZNTamU5b3jTC2HKieGYVj/AT05wIEDdc2calX7hw5cw2cP5JdukufMxoDjA4a22N6hudCLJdEJlROxNGkAxWNYV89ItALSQ6HQbZ3YRZPLILLkiaT6zs1IpnenOU/vpL2v96j9VVeKuFB8ioIBZdDCwVu8PK1W/s3vBMZtXneu5jcxQiNcIHtKQySxfU0OjrsG/gMxZDKzcGd/899mruWmAwMToWkxv5GHXZoBhxi/tQ32H1d+93er1RtHSNwZ7MavpBKuTNAzThuQsqZ1+NGCzG2X82hwrZPVD48Ql4i9v5ZLjgc/5emYcHIOXZRdRMIZfbMxWEZFrfiO2joKZr7BYcysvwomifaO/BrAO/zhMMOoUrPBftKEYmQ8JNK8i0C88sXjqnSvsWO71410XKXC4w/E7njGgPbVSrKolo4WiVyx0/AhAb06+EWqUjmFNghtqir0ASvTZoPaFB5gOgOmbwMWjukfrpFoLijUDM5Oy6Xf9BHpvOJU3H6gby8cWPufQLmlULwp0hnRU/b82Pk0YfYlg0fYYm96OWoC8LFVkf/VTbKk2PS0+l2M7i0Z9dKaMY4s76ze5DzkLL8Rwn1aNZsF5iP//qyiSfUlSdrRAR8QjeSRJPA6jE1aBzdUx62br6UOhB3ePrwJlowOiB3crAnmV1J+zHTFiU4lTbNdsXud0TQKgxZ93qBpk4w/OyXRoShmlZr3cuyyPDVRtJLgDwR4NpxvxDVnro/OhBW7VAj3lEPxl+6YiUV3sNDLMAJDXtXl3bzvXt0PlV37VeV7VFR9eSUFSnBD7mHv7Os2ZHC8SLK8PqfFSRQHRqmR3i/jfbm7YUU7j2R3LvfjrKe4eexV1fgTsF6dh4x0lsSgOhgGxf11Y7yprRFQNY0wv65dvdxxi+Akcc5nqYEE=
  template:
    metadata:
      creationTimestamp: null
      name: unifi-poller-secret
      namespace: monitoring
