---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
  namespace: tailscale
spec:
  hostname: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "192.168.2.9/32"
  tags:
    - tag:k8s-operator
