---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAGeQfcmK3gz0nlZT7JCh2RULTTPvqh9TOBNc9yzzPqP5dDa3JP2nb3vQRv1GszcKmulS/9QU8jTr1KdvAd9y2kqraswFg7lHpZ+p3y3gZIwa2NDKsk+mnAfFfFcI2HLFFFnkd8/at98s8T+03pgjgPPiyzjD139poAOEr8QnWjeeUgeKMVJ3gNqrYju6+yHTbf+UU0WAQGpMhkb6g0tmge7BlkQ8UI1gwdgzruDCi3Sp/golhDpAey1jTvv/o60FNB/Stdjgiee1g/QNKUxaU+Kz/ARqsaxxfoNHUDclSobx4uxIRvw3Y638CICDp+jWFCsN9gzsXSbJqTZIWz8Yl5V6OyVmTIdoZ3DBkozdlDFvZQnJknYY/R1H86EEdoJ/oPKvfeQ9RcRJl2j31+LHAa4YwokFVeEolU1BiCPaVqmPnSCxIFt5CN4mU2peCrQIMiOi9ZUYRafAJAWE5H8pCqddNDCwf6BLimnmxc+jleb5d01UtYzBmmD2Ig5CmZ83tpHNMja+IaCktuVyQRk83OEPw4v5YvIjK0msy3p1QFFhxGUwWEgfnJp7RFurSzpCuHlltSmOqtBmIaDd8xio1/7xBA5TSII51VtIYt73BXT+3tyBNVdDIihQfx4i0e1Y+t0P3gYHjo7He2htdWNvHMwPlMuaChiT72a7AwJsSuNunfXDtp+SzmEi6PrfSdtaHgTa6lxbezSmXR7spWgKM1vQ==
    client_secret: AgCdH14LVPs45poVDmJeR3XyvrjGoj18Q7FzmRDMXH8nmSfECoHYxsf/2AZhDsk+CahWEzY3wxl3yedmvsrBnvh8zIbzedrRQOaEny4Di6bFQcTGHtPDwvC2SF2cLhFXsYk2ph5RvcGKfhspbucKyNqkXMNVk01rpzLdLRxp17shRRb5Ew4I7CgcTrVo1HGP+I5NckkOHY2DUajl/uwiAZC6PWi+7JQloQzdc0Nvx5xp7MvOAN5YeZwEHIp8/A7qF/ji7nv1xGyQPPVxz8UAgkyDNwuOviT8qpsqYO95EMbon7OQFE1VhqiHPb/8hDQ8z9sxc1DCcHdTI2Wky9bedvRH5LlDGJBAsvYOF9tevkbKWnmG3GsHEfNguLJnU1LQMZQhdAMsPHnFDUClySoUS3Fan86XMrQ+QQBqB2vYORSxbk2B9UJPjN253Wr4BGG5CfBnqkHbejZvrkrN20t5HisFPg8xaKfkmEvtYse2E3Lo99b8KjKD+qvptOruHtbOgBZdqL+pBEhAmz/6XUwMcH78ya6vyhDRVDuqVcsUHRisbZOXPW3PgYitEobaVU0bcdp6Y5JFUMzGKUSoWQq00NC+5dehAv6eKRmqRFqH7mwCwZY7qZJpjSp1jzX7AWDVMXa9YqY1z384Lqy6G3/bSLfWL+L+pr5OvsE+o+/ZEdleEo0enicy6gZzJRVN3p4kMqcOWbcVnTS9JaUAQwovEqwJY5fabaF6dztwrfsFBVWuvKP/R90IDaU2X521Hjq+0rfdftENiNyUGNZXEWJ2uL8=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
