---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgDVzl006JDF9NvVjkj/hhtantj96nHadhHn1HRyMgffq7ab//XL2J6pjNE5vL60fKOnmGxHkwisDHcU7UfWloc0s+f6noLvS4trCF5fC4/2ZHyQtGOxP5400Lak3MHuavQyoDQkj1+F1dlOjG5572P+k2jyFgN3YbMOGLzvQjZ3DKmf3V6J7hXG4uRoiVyeBS2T7igF7/UeGcZYR0UJOnmU7+jZcg5xdAT8d+qtVbjqIp00Dg0+BZkJ+J1IiRPa0OOzYsHAmeTdbbuXvL6gO4LitwRIr2dBJ4AzANZjaw9JPVeGRBxLWs5MW/cofjYSpBXKhJHdj4ZkrXrbSCmMH5oW5RW9dMM2RkBwknym1l6jFTxpxGxysmoFVcCYPSoPTdBFP9XuU4fwIAUokjdAqv828+fIajD2JGDpbeob06Fdsg0k2GZCoWbwH7GlJ1X7cuL/eoWht2sbA68P3Fl98UXWTNEy5XQxDfmNfdEPff/nbCn0m1XgMGzBWXFTX3S/8/6EyLWllhwzcXzMFfHp/u4fxJpfC0F3P/lOJtu0QEhianQAQFlqn1c43R4TBLT8C8dEMih5QZromnBWrEAwG25QD7OWvb9vlTLCcK8QQfJZQee0MlcR3Wt7lGJplcGPtob4AXgdjS0sq0JksDmie8yOb+1KKZFysE9WHw5HuUI0cdsRwgmO9F0HDDDU6Yu3LUxJ4zrgyvuk8RyyqZvCV1iQoQ==
    client_secret: AgC8TS2qo4AWRweYszJVEohFhRkrmudSXnMTh83OZNsgZiib70oBP4OH63ibFAH7F2MtEr5LdGVN2/gapuIA+wEvJmBuqb1cX1rxpsgOJGKw2XlgF9zh6nHExt1OwoaoD/gj5gLc2SQ0ScbCQvfZQIHVDLH2xeh7kj1mWvsZNCkOKoOZetAXxJPCh/H1UKieJ09NSrsIGo70Je8eEcpP56fN0wWbh69v0QYwmcu3YP/1y8q5pRaDo/aIco8QPjnlSc4wW3SYfPmvBEJNRbnKkAanhsgyQQS68jjtezD+ih9jfi3gTh9xhnpSazWHuZTCLs21nm3tpnebLOik40GowI/BacXOvOb0ezS02hAMuyIX7IVOJ683nJSg1ZjNWwDNRFus8icc/ytPr1H6hq71WmJQ9zJi+DyTKbkzDZY+PItGPTGH1pQKS1aZfuAcHjurv5597ZxUeO7djChbNxz8uYMXORe8QKgEqbL/6Iu5SMnk/GW/2jLAYdB0r02QX3wBiXPbjs11PU7nCOWBVEv1VcKKaHTEZnC/fMfjz1a5pd/nSncfaMEkQjhnDWnF4TlIS+1yWHVfBCs5pi6ovLw+STLBkGFsVwl+6Fnh8CweBuX31/R8oLqc6B7Ryt4YSwyf9/uxA4bcp46Jf7UrAQm6KSuHwsXAmVO35t7gkj2unlBUEDDX7p8qLR/oBTUM6RNJrIYEZW2qDGAKR+gDmBCfBT5yunI1krfajBoU25JM+FMIuHbBazdFChBqIt4K/lzXxREJdN7w7kHI6+OyJJPn19o=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
