---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-cloudflare
  namespace: external-dns-external
spec:
  encryptedData:
    api-token: AgB+ezI7hHkYMeJkw5mpVF0z5cGWrfYhJeYa9YSJDMPyfrYAmz0Hvch1TnbDYeORcmix5OiRWkudBEFGgjzyDaPxRRx3zk4R2mtao0oYLPUS2nZ/Yvyuo+4yQjVHNQBhE7dCzI/bym+84wF4N2seK2CsDBwI9xs+VcCdZ9o5Qeb4v+++JtmDPMsYWpJpH5/DJef2L6ZesBOH2e//D0ax+kxKPBUEJI5jh75ixp/EAFcwwWltdaAYZQNjVkEcgr2zTrVCsUe5uHGHwUlnJnNrUxzruXIBoTnAaRY3NplCE5tW59mWgOZgtbRoqo9S5tk8kA5ej1a2tEDGCltJuN9ItyQKWYQ/6fnvSVpjF85hKdnBWUGaBRQjUDeB5z+a7xRvDdjQw52+SyMFRJxbdsIKwnC6dgeoRjCLYRo3wHUaztIgkoEtgIRppkkx6ePMcYk96yup7B5+QqxP2tzkMjo1LeNLGhEfLTdPbpfCN0+C+toUg4guGgHjIF632+lg++ZsxD8zyYqAv5bBwg6rFXk5Fc+DnsQ89giTVGfJ5jE3OK3pH7dzszgdaU8TyXCzQv9DZdtd6WSKDVX3tV2uUdY+HWxrkXipPbd+vYUaYfHtv8/wR4qCvomXH8bh81Qw88w3dPnjMkUeCa49Ep5oASi7mKbtaZFeLlBc8M8Pygo2+xasP7pCIPM7yNl355epQSw+drxwcWKtEJdAd978e25y1xDS6agZVxrHFDB7hSJlIM+XweR+qpLxrn5b8cn7YywpcD3qL+PejA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-cloudflare
      namespace: external-dns-external
