---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: blog-ghcr
  namespace: blog
spec:
  encryptedData:
    .dockerconfigjson: AgAEcMNEgrPxVqdQuOHgq8fyTk9ie9Mcsqrd5QPR6i2HE5iDkC4bpzeAC33h2evfkfG95z+wBGpXWZ0hIUPTXj3i8hN2FTa1xw1/5xw5mDWeePzGid6fYbdCOZVcT4UEvsJVtIbuyCsLM5VcdvIs4sTjv6x5d2d5SR0eTp+q3fRXMEwEd8tL8xkcDRPxSu62vbDQs7Q0rBeAgWVKlL/+DzzZIsKUeGSMRmYhXHuVw415204w2RBPAVLL80hp+g80X0xWXf1pTBh0ifMCi5qtX5lC2tqG4kea3M3Yw7s7gjM9eeLkwKjxKFoYi3Z35/qFIah1ATQlTYORZV4gsZx0Yf247kLR3In6Kj74RmlwyVAJ1XLGoM23AJWw3mPPsn/+qZbPhyrK1IKBfmyttNLv4tdsLL2ZCHpVOmt6mq1q1JACxvpEfOM29qUzSCS5fCu1O304eUcxbucPg5/VPJT1CJCGdR9ADrGgeuBui7isuNxEpcjAPWPYYlcIH/HraYoW4TWFU093WDEgqNPPqJMWWTnRZ/78FiQF9VMYV6xAxHnA4Svveu2FoSBKBj8WkyzzvrkDql+k1SFCnQ1DSZX+19zw6u5NwkLaUxA1IEZ36VSfsLmbRU0sdoMEN8BF1sHN9JHNSDUNIIxodgrimQmtiy0cpVhgRN5GXi3yhGzGVcS422SOMHq1zfRNpKZQBt0gPC0eXjfbys3l3MoPgzwAF+/yq1+pyMB6XuCU69YCa/mIHfhYzzLgeQnaOhw9UmVSpB2Al5Drzl/F8++LBRJvL3gxlsxu6kwEIqIO3Xl0TG0FveRbVT8sJEd6z5aepqF24pn6D4+a5C3C6dmzehVR93iOULf6NkZbiULFECSotWwsAs9x3xF5uhsFMPAyMHY6IdG8MuFigmDTrhlCo/8jYIdIUAMrv5ZBl76YM5kDB32UIFBLFywPhFRoP7U=
  template:
    metadata:
      creationTimestamp: null
      name: blog-ghcr
      namespace: blog
    type: kubernetes.io/dockerconfigjson
