---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-env
  namespace: authentik
spec:
  encryptedData:
    ARGOCD_CLIENT_ID: AgCzX5k+G9Gwxk/ZsLUBD7W0CgQQnQqBZDF1yFDO9sQK3Efh/b1apUDlc4pVsWPPcOWQfGtXz/l/LqoWbLIsvxYrRrkhCHEa+38e3YDx9iP9oMx+Q5GnOPFgebAhsHP7cLKPdpnfv3tNJyIK0tF/loFS5Ts2I2TYtUbSAmABMU7ZMduKMUxzA6tost3Fukklxy8xSA8XcW5XeVoGFR/tc71RR5nfF5H6XIAn/HXAAowr+beZsjKhdhmZHINPN70+CIW9ujMILm04rmt+njW2dBcIZi1lZn+ZctX23dvPKkjv+tNxhWFiP5l0u7x8O5kaU7aoKL8bElWGrivjQaVCc2XRnITQP2eMJ35bhXNXrjR6TthNKqH8BxzCErhStc/DJ0IA3y6NYV/NaXZ8NocHRyAoC6cR3RqebLfZYFrht45M7l6VQpPIK2Zf6Sd4Sov6BXv+7NFXOqcyfLnW2VSd14AMwHq8oPepwEiCtYYbrbmhlHM0O3rH8nAqPwreNK/l8em23shqa9eY7M/cYLI3GSBmKBkSHZv6d0RDpJbfBCY192wycIex4CHO0RqVuYNtYXstCk/N0O4AhB5A+vI989pRA/owKhB0JUFgY4ZooyS+6C2hWWkpV8bS91tUfqRBfIJdGZWBOms04tQDETslT0PqANspONVRfRiVY2s0T8BhxlF4c9G9T0DPTT+9fx2UbAc0L6qjM6ZGGCGY36EDJcCEJORCgaJCUSKd4t9w4bHxnm0W/G0=
    ARGOCD_CLIENT_SECRET: AgDkd686KljPyov3Nz6QMkr07f2w8U0e5HhtXKZ1duHyEv7vGVPj5UjJCz3UL353y9DLAiPPKRMhnmU/xX5Q9dS5+LvdZ3eccu0SM3mgIhMs4WuN0rsEEgo5n24MadTxohtKcHbp7iuo6kHBflznTpxfTX6+VxztG6DY5f77D40rhq444E+dUwedd1f2mzymuLq2rqIHvi7wOsvVYd+Nx6+8HRAy6oMnO43R7InMSMtnzHzlyOykR+noDNGPfSJfqak5AlNb0K78RRODc3EfXQxIbQi+GYXUWk0WZm+goHYMsRffm6sM1zQTwL5vC7HRU7myTNeGv/1urigEquEA4GG8TLny/r7J0BC+8pnxgf3CY65oWMcW1A3cQUDV2oej/2Um5OV9x7Hv3+sE//0hsM8AYQz2LQ/4BIY/nfwuQK5LC1d5ZOkwA3QOyn6HrClKaff+FTv060ELovNBkYjlVo6RKvgP/Gewyf5Vg9tulFzfUgLtdKFxhS5pwfjt64V5Wu7KNbKrYuSic2+yAqebY45AdLOsBiJXAMjF1gGd0c7KOhis4YUHh4ZaaXGOKCuy9B5VleVfDcCdlOBoXVtrp2MxxjdMywtMZetWFM6NikCMQ1J+O0q4imO/pPDguEByvbzDd/dKkyeYooXaOzbHvPWD4MgT6fFMEfCJuJeCv7CJdU8D4kaPVOEbDNOGBtIdx/kdLP8uMy7ghdB3PJLUK7oWvJEzshWcCI6DXDhX/BqzyU/IU1wwvJ9GA1lcN/AcE6qaBn3L/GHMmoe76gEGz1B6GYoYhX7VIQ8wwgn0Lv7lFTgek+6qM00WTxwtFf8c09Bb4NE3nz3eNQBStXXMUPylGG973Vu6pJt5Zm7bTUaBsQ==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc-env
      namespace: authentik
    type: Opaque
