---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-env
  namespace: authentik
spec:
  encryptedData:
    ARGOCD_CLIENT_ID: AgCSS1m1qSAzOXYqitmgz8Or0qIoDDUX70KgunK2TZ8l1H7AbpGqwcfMglaJ6UQZlQP9zf40HhrscGJzwfqXJ4GhjT+HMbkTKtT8obc83yNepQ5y9+sjxW9Q8l6VhufWbfKVc8oAPu8njbAc9PM76a7XbwZWqbhPGnN+Hy5kgPR4ve5qgnNcQvADA/XJGUKc/nd8wUq3z85q9qPDXCgO1IvC1mxqouQN13E9UWjJGtrsJ4Mk4FncwDEHxw+asDByw4ezytj/9dUGbRyS70KPI1KKcdIZjfFJToVRP95xy5MdJBrP5Z8shMepnYeqXrpQX1R/ZBRVskAAQKK5kDTUph67/J05h9G6Urxqt6aYq6XNCC2Ohj/TluMT88Jc7a6+yoIgC3gPQ+c0gN42WBMsC6IOdHdLPieaXk6zuh+UAW/IWnCOMtiR+M+S+/ipwfnhI26PPT5ilqBJMwxOnB3pFgrzDXfTGGnIU3nVQCGMCo10w8nm3ysOuGfRHm1dpX/64rkRDBtv1iU3KcDANh8Iotu2WHGmSoi29yg2T985OoIDc5aAf2s0bzi0H3cI+dqSZlbXR9RwRQpPC9oW3AZU2hXQ/fZxAFd7oTe72cC9RkK7I9cC7uz7DELFcZSThErxv/D+cyq+VSSAYlk0OZ11Nt9sok0SIFWxa5bDuaja23PbSvGruXK/DYZXK0D3bS35qwhjEO+R8glq32/z8DMW9lDZ+QXSR2ecmPzgT7h8ZrGnpQYYxhs=
    ARGOCD_CLIENT_SECRET: AgDgsIYn5Xq2nXssQbaIY8EhmVaGhaar6M7DruBKO7zQ25vu6HTtA4mXXly0IylHWjTIhjmM0Kl/6tL9dcWCsDWFFuK1GEkJlFywJNFRQRLtSZPhzyKuUTNo2u8ba86xSdJTdxjWTv1f69fkh76klEpUpWoRQqb8XnIoReKpIYEcruDAJbaE5+BADPzgZNnep9wxSi6Ze3TqIeVD7QD4a1hj3Nxcqq4MfdkhAVgeXdQ3sKacn45egaemK1tR6KOO8q2vn9yuCnSgWhLgmmV/yRM0h7fjUPbdfCpBQm5iXHSuhNhv3IVg5HPJWG9NvnitLGn3nf6Yd1OvK8yIMnF4YVjA5zEEvz15gvMIDDXFoRkpdyCJehNrowP+P2F9podvDcvGkjOys81E2Tgj47BU5J96Fp42EMgURfkT3aHPkCrfGeXoihHRqVN0ldFs/7wyGmG705yccH/2Zp44Ph6RnQyX70xGAkGuwY3B2+mfCjeDcee10TT9nhYfekaOsuyx1T9XIUan9DVsCGeUNuh+GKxNsYabYdwQ2spQwIvTImpELqPFOAAPZcunXhrcIzqVbJlsX2NV6bQ2EjsPLywx5eEbn1iJzQt0JbrgyqkqXlEY1gvWwpcS+r2bwVFcRM0mbvgzP4hQ94J+wTlo4iWBcpvrR0MuvBgCd5IdGt9ufdnKC0aj5Tjo3SoUzHb/oFBwX5Cp2whpBjwyOLY4tVY2uRdRFI7CzJECqE8zJEM8YKOS7a6qezrAFunylPVTDGEy4gpqLCfW8HtLZz84ylzTuQO21rzwcPxodLJ2P5r11KrlAPsdzwBafuIbvXeanXjRSWTA1a31qzhCKdBF7au2JGL3s2jHsRos5C/IUiC5J4UGhQ==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc-env
      namespace: authentik
    type: Opaque
