---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc-env
  namespace: authentik
spec:
  encryptedData:
    GRAFANA_CLIENT_ID: AgB/5qp3nPs55j5v4n0Irw6He5E6xKDYBUi5VsTmL6Gumbr42PdAcj6yh+JXpisashUtXksx+aMTs6yukNaH5fqUL6J+QZyjGiU5NTSE1i9rJpiOIPNWQEtIoyPbQ5J6h8kl94ChXCpqCzhtbNNynbCMmEsExSS0NVfwSbAhFYEEZgamOIsyWf4sOtm82TYE2KbcsiFIlF8g29RM+PLPaJzyRXDNR2ZPzAGeHEY66WTsA5kU6/A4axDjSVa7C7P8T2weG0jDx6md1Afvkjo0XDOPMGwuWp3OcSjGFxMUq6q7tPoYDPr4NRYXRw5HWOoq1z2zjow6eSlaGX2zOp+l90BPzmGL60uXiKRVXzX+wwaTRk7oFalqEVdyfFDC4G/o4noakYkk1cG/q/jMPbB7qQNMd7UZFUK7Jk9YqvOnLOpICbHLnboDvBXRYJ02Ue/9RoZvVIjXtIRqZgDY3UGDcGe4U2U5aiv5BMYjlWpw1gj5xBrF5TOvJ7/iQX9AW00DGfiDtaHmBLcYxvAwJFrBFn24WMqYYxiJNo/LewEEdDFV1hWh3K/nxzF/4vblCJYZ0UgHNRdzMqAFVYTInNpb5jxJ3+UWPGrhMlf9r59nTenqcd39rOrgshzcWpsM1U+33i3OzhCpbqITfHhrhP5zVh5rucz/KLxrltUpUaft0zAxUvbkR44tXZaKUxAtRCADj0ombc/9tzv+m8Dkz2pJ94vf+89fAeocmckFUHza9JFG11Mlvsw=
    GRAFANA_CLIENT_SECRET: AgBm5gGMXU10mTQgkHKPDEnh3YAzfGuE+ROQ0BWftqhJqcX0swnYHSkqFgDnON7t3OuKnw7+o2jYiXiuRXLoD6NviLcoXdg1E1TZYVH6JQRjv5jxYKYEiYlSBivGakwclW62pZXAUg+Vbu3zfToTRNXVqiX2Jv47aTJ8D6nbccQj02Ot+BKX5r/RGC/fSXaGnIx/GPQVPjHTNks4yTE8VyIdJ3x8XzbU210cuwQ/qB/R8iqAJfB36HEpavwdkqdklEiOm30e2TC7GzGbiALFP9GYzJuOWU2kKtYoYLvYon/cAQURFGJ8EMlUIYoKbamLvbab3G/O2hok4d/MsuP0kATjMbeYgYdHTMT8PGIKcyHRUyespgkPGYnGfgF9VCIU+v94MzqbgeotYLqWTPHo7Zx+fbiSNHxrZJ+aUAHp6Gm/mMryGwRQmf09htBn66KSEL05UykaFz8vg5nd9rJg44lNEPz+otCzez9Cie9sQy87ucKOD2sfioR9mGyVodn1rYs7hueO2dwCjxe7Z7o59z52aJ5xLV79mrZCny/L7mWHsjOcqtxFEZiaC6ZOWd+yhD7aXJ/UOHBM6ul8CExhhKHZGcJV9QCuGlvMj9r0Sopqhii/4mw+picu45u0vdXTNKDc2cvVOKrT38dmYWVhyhdDxIeWFbq+QZmTWalFdfma40aPL811MJA4QlSJeMSCCzf7wAxaLT9Qcxk2t2YziMCr7hmSdiSuKW4/wz4b1pxm0KnzO1oXEF2SHAyLA+mRtS/dvKC5TW6UGW1TQ1DisGC2bSvea80pcLiRtOPCRN8+hiTJXv6Kk2s7fB2ojJRTpLYVl69NMvamWr4SnMhHX7c6rHclI7JDsjHEAtSmFGcphw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc-env
      namespace: authentik
    type: Opaque
