---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-oidc-env
  namespace: authentik
spec:
  encryptedData:
    OPEN_WEBUI_CLIENT_ID: AgBm7qyoQJJTJVpBUuYU0BIk8bfhP703JDE5rTAVorMZpb0bnoZrvdDKhrbUlg0qKu6zzmipYYLh49IcKZ4YIBCpji1tH3b/3cBtWjHYebKre+o+Yu7r+j9c9eNCRAaQz5Zg3UWH1+8/pcF39k+t4tAayygUUfYudQ/zh9RbyfJ+pg1ZDdruiAFioKh0mamGy0NaU7/pDPlzWsNKG2yKq+yqdeIr8LxwnwwjfiOB3lfe053xJSkK+XqrfXHYuwDjguX3aeJdXc9hkVKbGCn+SIrbRk3WFkAoKLvixTb7pNaSK9tBHXXoPQSVmJKM725DNThHz0NNAH0YAx63wqor0CC9q/sZdmj95Vl1tLrxzx46PR0STDmPOptWnpPiNNY5yX2Lvfcm0XnfReKxSPAT9FENd7lgjhg21jSUheScLsJAEOnyWqWtOl2BG6gZWu4xw1Fr1Ohk/lg19vUhbefvu32l1XxHxdt8Rjwf0KhiLqYu5wKAQcsKXF14ds2UdmNDfoCd17olShcKoEluMor7o6t9tsv+EYacgBKJNMFRjHiDrSeCN0VfwYMjDCKWJWreUsr5u5b4WaU7eA1zVv0xHBUDv4n6HiviMaHtOiBx3LJ+u+T+/Ur+sFkmL3zKO8RIEcm/XqpGwMC2tQgT7Rj44N1NgY100PJK+z8vnxhinuzA1vPolskWM9XRc/rtSRnjLbPfm0rcYb9yTB9e5BkjIEz8I0VfRq4VWSCMvLR7YX7wODeYlo8=
    OPEN_WEBUI_CLIENT_SECRET: AgBMfY+FOvwvO5U/ZPaFC8mr2QhNrjul8W0tiVVIGhDq2Rf5M0SVXQF3w6r/G7rlC8aHBOGC9CPKNL71GSeWmTwdpczPpinOPAEJOgH0/SUoKv87AgwXKVqP1slKvMtLRnJQdT0pnoyhiULYBn6l/Qp34/UJluaPN1UtvxbqOI2XEonhhUMBAV4aJ1n+c7cgCNu31FZKEYPSWRLHiLfWIi163Sg/YF0NynjlOR6w170oynV0E+F+6zCPcvvef0dJ7nKgrq4RhElbtmhglAHd6eu1zSPZsOeXtUNQc7RwWNw+4XUtguAPbSUm6YNHAVf033DdxTQwSi+AIATwpk/n/BpnCOpps+Qo42hJuBFe1VzvlfmsjhY1xDP5OzItWJ2Dq4zEf6X/FaSQAZQj3ODkrZfk/7rDK65p5HmfOw4RyY7P/r6dLfSqmnYqzjeqCMmNuD7YGZYpeGaA7h4xNJTh95eKY//7dQFBUfdoPBOHlltiCoCEBYsQ7htEzv/BZOrY8dC+w/aN96MCKo/cYMN4hFEz7EBD2yrKs4Lo2YfrMW3lXj/pDi/AoUc6SsF4PX01H94ZWcD2VozvM+Q9RhWNz+1usl0u5NFkQM0avab6V/37x7Euczc8qs01xQPrQdtl6BUcstr0V8Xw7aVagFDR7ORe9DmV/MJlkbDM4offrjbHVqrn85Lf18vW8U8hfWlcJ8lFppsfzSbXz4WrQ3MsvKXqn31UcsFcldeIH2IKYI0mRBH+96ChK4NSkQsK5U9vN363Dyap4rLK73itziPV4n39cYzi581UFpMN+aAJyChu+CnHYma1AWZTqFWUECVLEn8wy+Q7Qmkw35PwwdDwoykatHmRACI2iVoM/Y+qoSom5g==
  template:
    metadata:
      creationTimestamp: null
      name: open-webui-oidc-env
      namespace: authentik
    type: Opaque
