---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    secret_key: AgCTMnv+W2AATyjp4CdG04CIojXTWxme1cFaM9ypLjh7zLIYFdFOFsQePCz7nZ0TLmeroogXLYYbM+9GE3M+fChYIKucZDwA7Q0VwfjbwY8uXtDVmBbR4Oj/82ROFXPpIkANCSrywwTbFZ7+LgK1q0ofR59h0KLyHDd2V5n6VoFtO530icvzNuG+f1KoR9trlE4bHQaq+8gch1NBDzxhUv3Dv4wndB174faLKhApg3IzcgNHNa/hs/EL3lHYe2dsJ6IAjIAWstllUI4+/zmknfbpPAa1StSfaoLohWgAI0it1+VFBKPC/Ro83jMS46VoUnntotk0NYXlwiUkvShK5q06mP0YKl3Xnq3whG/VAyCS/m5RNFs9NnrCMcuAc9SU5gf+mnxU3nmNNudMgrw5cyV+ZE+qIBvrCNQG0PpMwtWcwyOZTYhWzHqc7D/zQmT2KVdSTVMlzgbXC9n7G18Fa1CK6Clp1QstR08U3qJ/KKyhCqgOnaRS/KfQ9YHxmgZA0iJc3K6woEWZzbF/euEjpfkCcPBEtpr1lysOmFbzPm7AXIXI2EK1mz3GwEpCGGrs+Nq+ab7HFSIA+hUzDHFr7DjBWVCWMOI2Qb7MhWYGEIlRLwl2NDNj7HMTVOQJE1MvXtqRv7wYXzm7VhT1E/BHOYih+eQo1S4nYPXM3Dub3Vrw3mQHAf4fA+r6rWXgTDOWF7+2o7cGuDtl0a8qnEpMhaSqah7EkaOedyr2GKPIJ82anQxYWqI+TvVu7U0h8XDsOWu05/DAe6/sCqx9+7pvV4ht
  template:
    metadata:
      name: authentik-secret
      namespace: authentik
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-pg-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgAVxela7Aj9G4TVa8bbC/1kQ7n64uP75JmzuyRdg26au71mtbZk/3zwUIGBZgbSoLsR/9bs4sCeHw8tfU1NXy/rf7IifMGA4MMblKnws8RQekkvU91SwnndpuEqiTHFdwfZoeXYW2IbRmK2NDBaryEcg7CaNSMqoth2nCoVxKNAk4iJf8LrYDgmwb4yhZdd0MnV8eudmjHY3dqORHeol4OGdnZw0LcGTBEm8Ct3SraOnOUnWmb/dbcBxvaroq3aPKcng+mthdDzi5oSc1wQSWqvDo0utP/kiJSdkSr/3Sozwv5uFCEpS0KYDw8/FoXglgajHBcI9Q8/ayiKB6iWqSz5iUx8ForksH5Ig3Atx8uWCKhUE/Z9vbONoSySZqjW+BXtzm1mqF2NwMi6Un6iSt0zqDg7oxfmDsGAYk7+n6h8EIf0CeFoNZtdZxGnGidsM+z/0UT4jvupac/FDKG7uPxvnjh5dw/+p9WQsB80HQoOAE3h4bhPNBjVlWUDuz9PBSffpbXbcZpph6/u9oy8bqFLqqRyLKkX49zH71MZ0fU5TtF+FTzl7nFv+t2tMTgQj+5aHZfneLDkXuRUepk+B+wS1WeAF0K2eT0v+HXtzJURA309jvEPXV/ErX770RVQ6BTbBV+kZicRkaB5HRVG073io0o2X9+M6sV1p6stLSKqkCj/yLUA99gqfLIc36gL/5I71I3u3rraQ20so1il0+vMK0c65B5KRGroHb3NWwPJcA==
    username: AgCFfEKcm9SMZjoXoFLLelZQlUUcOxCeFnMiyBGHI5o+5PgCg/g1Mnc14L22G4i7RI6Ht6SAeAXiyWE8kluJt2W/vYhXfWkTiGFgVsil4dnQtqqvXCUpIU9d5rIRHKCrUgyAzv8+GcUxNmkvQBXuLLrZ7JHyC4KhZTp5WsIq4WFryqqV+zSKV+bNvuKrpt0Hw1hZms2UOK7cO1mXN/lU/EKhLn5UtEpHVAbv3thVDdESLaSw7iqiWRue76iAaqmkV5qpejPP5/An9J0+o2i/5meUhZYqDCT6ZyezBnrbj/ZM4fbwg7UcLxZffS5vbTz5Zk4cxNlw/qIm2xxSQcbdy+qVcT7LL26mfoObR3/yfbHDDl7BCOcKw7Y+/VAjJb5fcdGz7V3LdKa7/A0vbUJWZCNrBp9TkWGPszgOX3J4mNBbvjfBmK9z4q2vDo320LsAdvbRP3SDfuAFzMr3bUF2bNRpwYgq3ncCBRdvCSTVj15Hdkn6EzBz7P1QeU7pr2d1EWNLzRIw5Ule+3lNpIy+2OONKRyQZM2dcHPzLW3GEuoDaJZUM5bkFvqZoGVVnGxCXoXwsKHlP5SmjuYuktaU9kmdMlw/ZcXQm6Afx+6AZkBE1DpW2To8a4ZNw9e1rxIV5eL3duzp8/IZxwWwXhxfP+a3GrD2DGbOdxlLcsQGP2BJKQW8/XiptD4k/iUxtLMK919IzgKkCqzyylc=
  template:
    metadata:
      name: authentik-pg-credentials
      namespace: authentik
