---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBXC63hPD+MHm5dTImJoyYwKIcUag5WFydyMMBqRDVU68zkbTEYVqAx/P6HFSJ6zrfPBBPuY+Dv8lpNqz2NfZemSq+O/tLSYsoHhBB5gt4rCwHfO7bQ20BD5dM7RMX1Pkp96+TnJPEROOLdBkSqBDJuH54mWGElFJHjl85ncXvO6dNOFS2vwjvOTORonkE9Wl198Go3Rjuienow2B+0CoVOCwc/KF+f6XHN2co0dRwbb4MSIZ2N4W257IRome9PpXWvmljqwMrg4d5GCR9OhNq368HVw7flBDhybn39omHpj03MoDJA6YToWiK+zWWvP+BB/ReW+D8ORY+t0GowBe4oLjhL/zpGKiKHRy8NbMwQhsk4a+5vuOqJgD9KXu//6XZExjujQJhFB1C2euz0tBEswBkVqqQfxmnvyyqTK1h9P0wHzrqrz3MAQkoH8Uxrb4Ij12ckUGZvWUefn7LebGWI5LmAqvFD2IpsmZR9pW7CfjXrTwHDZFvJwZr7P1Xj620je1Ln7FUHNZVc0eyKOCQ3HTaBpz4a0f0ha5XgSM5LKG865WTrm9L3M6zKvlgrOW3PPyROJl7OHr2rRYrTbWm5H5DFJ7q+5J6OMHcIixk3xEXIyh1mdonpnkeLOKROZFWWE2iIv5cp5a+aeyzzB1mWT6wfAh/6TMOLYkP0ERNQmkql6KHABHrJ4/XjeuEW0mn7H8xb6apwlKe5Quy0Sywz9dJOxmyd/HTPX7m2+Uw6IB9MbCDbgtap8ii/c4yj9L5GiOMdRyhxfZFXpI+1eZ4KwsZQjlv6jiCCJDdwCFrGVgvLkLtw8CPAW0mdJVKCAxww2R0/3wTmfkch4Y/cnPeWdXF0FX4ncXSls0wj66wW0aq51OlrOmZ4xD+McCjYgdx43rdR1lIS2QeOcl4xe/vDh8Z3BT/xWmOC87ORkltD+j7htQeA
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
