---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-unifi
  namespace: external-dns-internal
spec:
  encryptedData:
    api-key: AgCD3XdiEKaQYv7uI+ZI6O0R5z3/FAhB0MV8+/qg1JPelDpZAOZH8B4rkhqE5LMGjydjUiSN49mrPvvr8jECUx9KadchLNa87Eupboymq0jT3JNTvecUJeZa8Sl7Af8NwIFUMgiSx3ctCaeysoMu7gKnhU9c88tUrFb5ici5LZlkDAN+XHwIxWtM3i6EgxyUWwxRjhFmk/NV5bAQEPcxenA/TIaJvroHJPjq5o4D9SZNcPcc89YzufVY0+7QEsTNx+8ab8Qqhqc6ELXWbD9b4QZXIyqMl55Wx+AoFiWjTorrUPveH441S2aIuAxt7ThPC40vt88NX9tk0zs3gk541ufP5uHGCQLnq/eFEw2JMiYw4bCBV1aDPPfeooFd8KmBYGmNj0Psbnbf68y0t964vTyZfEQRd0HWzdvy93Y7LaHxLGtXx3dOn4vCu08OR/BmQOd1MeA15Q/zgCwUb/3s7tPv3VyYMTFMvweUbFYcuhel/p5VFO+FZbp54l23UEfCDmP/ELABW5DBb+emccOXfFW0Ps/h5Ren1TXurGdwbTBevBXMyIjwG6kxlMCTEnGWsaBYbb/AH0NVaNmwNiamztXa3/O7k8YnN7/M+7CMc5LIzXjRd16obZSGKlpsOTMvvGSecW84bwN22Bkd8uSZOkYOe4nRGxUl6dQaQq0ib1HH/BvyyGqC4m7aUqWo14FIGXbg0cXX1UkvrL7EdBfLZoYZsd9dVfS4Y53BDanXNIwOFw==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-unifi
      namespace: external-dns-internal
