#!/usr/bin/env python3
"""
provision-sso.py — Declarative SSO provisioning for Authentik.

Reads infrastructure/authentik/apps.yaml and for each app:
  - Skips if SealedSecrets already exist (idempotent; rotation = delete files + push)
  - Generates OIDC client_id (UUID) + client_secret (128-char random)
  - Seals into <app-namespace>/<app>-oidc (for the app to read)
  - Seals into authentik/<app>-oidc-env (env vars for blueprint !Env resolution)
  - Regenerates infrastructure/authentik/blueprints/oauth2-apps.yaml
  - Regenerates infrastructure/authentik/oidc-env-values.yaml (Helm envFrom overlay)

Requires:
  - kubeseal in PATH
  - SEALED_SECRETS_CERT env var: base64-encoded PEM of the controller's public cert
    (fetch once: kubeseal --fetch-cert ... | base64 -w0)
  - AUTHENTIK_ADMIN_EMAIL env var: email of the Authentik admin user (first run only)

Run from repo root.
"""
import base64
import os
import re
import subprocess
import sys
import tempfile
import uuid
import secrets as secrets_module
from pathlib import Path


import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
APPS_FILE = REPO_ROOT / "infrastructure/authentik/apps.yaml"
BLUEPRINTS_DIR = REPO_ROOT / "infrastructure/authentik/blueprints"
AUTHENTIK_TEMPLATES = REPO_ROOT / "infrastructure/authentik/templates"
OIDC_ENV_VALUES = REPO_ROOT / "infrastructure/authentik/oidc-env-values.yaml"

CONTROLLER_NAME = "sealed-secrets"
CONTROLLER_NS = "sealed-secrets"
CLUSTER_INFRA_DIR = REPO_ROOT / "clusters/home/infrastructure"
ADMIN_ENV_SEALED = AUTHENTIK_TEMPLATES / "admin-env-sealed.yaml"


class _LiteralBlockDumper(yaml.Dumper):
    pass


def _str_representer(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_LiteralBlockDumper.add_representer(str, _str_representer)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_apps():
    with open(APPS_FILE) as f:
        return yaml.safe_load(f)["apps"]


def env_prefix(name: str) -> str:
    return name.upper().replace("-", "_")


def sealed_path_app(name: str, chart_path: str) -> Path:
    return REPO_ROOT / f"infrastructure/{chart_path}/templates/{name}-oidc-sealed.yaml"


def sealed_path_env(name: str) -> Path:
    return AUTHENTIK_TEMPLATES / f"{name}-oidc-env-sealed.yaml"


def generate_credentials() -> tuple[str, str]:
    client_id = str(uuid.uuid4())
    client_secret = secrets_module.token_urlsafe(96)  # ~128 printable chars
    return client_id, client_secret


def get_cert_file() -> str:
    """Write the controller cert to a temp file and return its path."""
    cert_b64 = os.environ.get("SEALED_SECRETS_CERT")
    if not cert_b64:
        raise RuntimeError(
            "SEALED_SECRETS_CERT env var not set. "
            "Fetch it with: kubeseal --fetch-cert ... | base64 -w0"
        )
    cert_pem = base64.b64decode(cert_b64)
    tmp = tempfile.NamedTemporaryFile(suffix=".pem", delete=False)
    tmp.write(cert_pem)
    tmp.close()
    return tmp.name


def kubeseal(manifest: str, namespace: str, cert_file: str) -> str:
    cmd = [
        "kubeseal",
        "--controller-name", CONTROLLER_NAME,
        "--controller-namespace", CONTROLLER_NS,
        "--cert", cert_file,
        "--format", "yaml",
        "--namespace", namespace,
    ]
    result = subprocess.run(cmd, input=manifest, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"kubeseal error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def make_secret(name: str, namespace: str, data: dict[str, str], labels: dict[str, str] | None = None) -> str:
    b64 = {k: base64.b64encode(v.encode()).decode() for k, v in data.items()}
    metadata: dict = {"name": name, "namespace": namespace}
    if labels:
        metadata["labels"] = labels
    manifest = {
        "apiVersion": "v1",
        "kind": "Secret",
        "metadata": metadata,
        "type": "Opaque",
        "data": b64,
    }
    return yaml.dump(manifest, default_flow_style=False)


# ---------------------------------------------------------------------------
# Blueprint generation
# ---------------------------------------------------------------------------

def generate_blueprint(apps: list[dict]) -> str:
    lines = [
        "# Generated by scripts/provision-sso.py — do not edit manually.",
        "# Source of truth: infrastructure/authentik/apps.yaml",
        "---",
        "version: 1",
        "metadata:",
        '  name: "oauth2-apps"',
        "entries:",
    ]

    # Shared groups scope mapping — emits list of group names as 'groups' claim
    lines += [
        f"",
        f"  # Groups scope mapping — shared across all apps",
        f"  - model: authentik_providers_oauth2.scopemapping",
        f"    state: present",
        f"    id: groups-scope",
        f"    identifiers:",
        f"      name: homelab groups",
        f"      scope_name: groups",
        f"    attrs:",
        f"      name: homelab groups",
        f"      scope_name: groups",
        f"      description: Group membership",
        f"      expression: |",
        f"        return [g.name for g in request.user.ak_groups.all()]",
    ]

    for app in apps:
        name = app["name"]
        slug = app.get("slug", name)
        display = app.get("display_name", name.capitalize())
        prefix = env_prefix(name)
        launch_url = app.get("launch_url", "")
        has_scim = app.get("scim") is not None

        # OAuth2 provider
        lines += [
            f"",
            f"  # {display} OAuth2 Provider",
            f"  - model: authentik_providers_oauth2.oauth2provider",
            f"    state: present",
            f"    id: {name}-oauth2",
            f"    identifiers:",
            f"      name: {name}",
            f"    attrs:",
            f"      name: {name}",
            f"      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]",
            f"      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]",
            f"      client_id: !Env {prefix}_CLIENT_ID",
            f"      client_secret: !Env {prefix}_CLIENT_SECRET",
            f"      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Internal JWT Certificate]]",
            f"      property_mappings:",
            f"        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]",
            f"        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]",
            f"        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]",
            f"        - !KeyOf groups-scope",
            f"      redirect_uris:",
        ]
        for uri in app["redirect_uris"]:
            lines += [
                f"        - matching_mode: strict",
                f'          url: "{uri}"',
            ]
        lines.append(f"      client_type: confidential")

        # SCIM provider (optional)
        if has_scim:
            scim = app["scim"]
            lines += [
                f"",
                f"  # {display} SCIM Provider",
                f"  - model: authentik_providers_scim.scimprovider",
                f"    state: present",
                f"    id: {name}-scim",
                f"    identifiers:",
                f"      name: {name}-scim",
                f"    attrs:",
                f"      name: {name}-scim",
                f'      url: "{scim["url"]}"',
                f"      token: !Env {scim['token_env']}",
                f"      exclude_users_service_account: {str(scim.get('exclude_service_accounts', True)).lower()}",
            ]
            if scim.get("compatibility_mode", "default") != "default":
                lines.append(f"      compatibility_mode: {scim['compatibility_mode']}")

        # Application
        lines += [
            f"",
            f"  # {display} Application",
            f"  - model: authentik_core.application",
            f"    state: present",
            f"    id: {name}-app",
            f"    identifiers:",
            f"      slug: {slug}",
            f"    attrs:",
            f"      name: {display}",
            f"      slug: {slug}",
            f"      provider: !KeyOf {name}-oauth2",
        ]
        if launch_url:
            lines.append(f'      meta_launch_url: "{launch_url}"')
        if has_scim:
            lines += [
                f"      backchannel_providers:",
                f"        - !KeyOf {name}-scim",
            ]
        else:
            lines.append(f"      backchannel_providers: []")

        # Group + admin assignment + policy binding (optional — only if group defined)
        group_name = app.get("group")
        if group_name:
            lines += [
                f"",
                f"  # {display} Group",
                f"  - model: authentik_core.group",
                f"    state: present",
                f"    id: {name}-group",
                f"    identifiers:",
                f"      name: {group_name}",
                f"    attrs:",
                f"      name: {group_name}",
                f"      users:",
                # Use group.users direction (not user.groups) to avoid replacing entire group list
                f"        - !Find [authentik_core.user, [email, !Env AUTHENTIK_ADMIN_EMAIL]]",
                f"",
                f"  # {display} Policy Binding — requires group membership",
                f"  - model: authentik_policies_expression.expressionpolicy",
                f"    state: present",
                f"    id: {name}-group-policy",
                f"    identifiers:",
                f"      name: {name}-group-access",
                f"    attrs:",
                f"      name: {name}-group-access",
                f'      expression: "return ak_is_group_member(request.user, name=\\"{group_name}\\")"',
                f"",
                f"  - model: authentik_policies.policybinding",
                f"    state: present",
                f"    id: {name}-app-binding",
                f"    identifiers:",
                f"      order: 0",
                f"      target: !KeyOf {name}-app",
                f"      policy: !KeyOf {name}-group-policy",
                f"    attrs:",
                f"      target: !KeyOf {name}-app",
                f"      policy: !KeyOf {name}-group-policy",
                f"      order: 0",
            ]

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helm envFrom overlay generation
# ---------------------------------------------------------------------------

def generate_oidc_env_values(apps: list[dict]) -> str:
    lines = [
        "# Generated by scripts/provision-sso.py — do not edit manually.",
        "# Mounts per-app OIDC env secrets into Authentik server + worker.",
        "---",
        "authentik:",
        "  global:",
        "    envFrom:",
        # admin-env must be in this list — values.yaml also defines envFrom which Helm
        # would merge as a list replacement (last file wins), so keep everything here.
        "      - secretRef:",
        "          name: authentik-admin-env",
        "          optional: false",
    ]
    for app in apps:
        name = app["name"]
        lines += [
            f"      - secretRef:",
            f"          name: {name}-oidc-env",
            # optional: true so pods don't crash if a secret isn't synced yet
            f"          optional: true",
        ]
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-app Helm OIDC overlay generation
# ---------------------------------------------------------------------------

def generate_app_oidc_values(app: dict) -> None:
    """Write infrastructure/<chart_path>/oidc-values.yaml from oidc_helm_patch."""
    patch = app.get("oidc_helm_patch")
    if not patch:
        return
    chart_path = app.get("chart_path", app["name"])
    out_path = REPO_ROOT / f"infrastructure/{chart_path}/oidc-values.yaml"
    content = (
        "# Generated by scripts/provision-sso.py — do not edit manually.\n"
        "---\n"
        + yaml.dump(patch, Dumper=_LiteralBlockDumper, default_flow_style=False, sort_keys=False)
    )
    out_path.write_text(content)
    print(f"[oidc-vals] {out_path.relative_to(REPO_ROOT)}")


def patch_cluster_application(app: dict) -> None:
    """Idempotently add oidc-values.yaml to the ArgoCD Application's valueFiles."""
    patch = app.get("oidc_helm_patch")
    if not patch:
        return
    chart_path = app.get("chart_path", app["name"])
    app_yaml = CLUSTER_INFRA_DIR / f"{chart_path}.yaml"
    if not app_yaml.exists():
        print(f"[warn]      no cluster Application at {app_yaml.relative_to(REPO_ROOT)}, skipping")
        return

    content = app_yaml.read_text()
    if "oidc-values.yaml" in content:
        print(f"[skip]      {chart_path} Application: oidc-values.yaml already present")
        return

    if "valueFiles:" in content:
        # Append to existing valueFiles list — match the block and add one entry
        content = re.sub(
            r"(    helm:\n      valueFiles:(?:\n        - [^\n]+)+)",
            r"\1\n        - oidc-values.yaml",
            content,
        )
    else:
        # No helm section yet — insert after the `path:` line
        content = re.sub(
            r"(    path: [^\n]+\n)",
            r"\1    helm:\n      valueFiles:\n        - values.yaml\n        - oidc-values.yaml\n",
            content,
        )

    app_yaml.write_text(content)
    print(f"[patch]     {app_yaml.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Admin email secret
# ---------------------------------------------------------------------------

def ensure_admin_email_secret(cert_file: str) -> bool:
    """Seal AUTHENTIK_ADMIN_EMAIL into authentik-admin-env if not already present.

    Returns True if a new secret was created (caller should treat as new credentials).
    Skips silently if the sealed file already exists (rotation = delete file + push).
    Exits with an error if AUTHENTIK_ADMIN_EMAIL is not set and the file is missing.
    """
    if ADMIN_ENV_SEALED.exists():
        print("[skip]      admin-env: SealedSecret already exists")
        return False

    email = os.environ.get("AUTHENTIK_ADMIN_EMAIL")
    if not email:
        print(
            "ERROR: AUTHENTIK_ADMIN_EMAIL env var not set and "
            f"{ADMIN_ENV_SEALED.relative_to(REPO_ROOT)} does not exist.\n"
            "Set AUTHENTIK_ADMIN_EMAIL to your Authentik admin email and re-run.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("[provision] admin-env: sealing AUTHENTIK_ADMIN_EMAIL...")
    sealed = kubeseal(
        make_secret("authentik-admin-env", "authentik", {
            "AUTHENTIK_ADMIN_EMAIL": email,
        }),
        "authentik",
        cert_file,
    )
    ADMIN_ENV_SEALED.write_text(sealed)
    print(f"            → {ADMIN_ENV_SEALED.relative_to(REPO_ROOT)}")
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    apps = load_apps()
    cert_file = get_cert_file()

    try:
        any_new = False
        new_secrets: list[str] = []  # secret names (in authentik ns) created this run

        # Seal admin email (idempotent — skips if file already exists)
        if ensure_admin_email_secret(cert_file):
            any_new = True
            new_secrets.append("authentik-admin-env")

        for app in apps:
            name = app["name"]
            namespace = app["namespace"]
            chart_path = app.get("chart_path", name)
            prefix = env_prefix(name)

            env_path = sealed_path_env(name)
            app_path = sealed_path_app(name, chart_path)

            if env_path.exists() and app_path.exists():
                print(f"[skip]      {name}: SealedSecrets already exist")
                continue

            print(f"[provision] {name}: generating credentials...")
            client_id, client_secret = generate_credentials()

            # Seal for app's own namespace (chart dir must already exist)
            app_path.parent.mkdir(parents=True, exist_ok=True)
            app_sealed = kubeseal(
                make_secret(f"{name}-oidc", namespace, {
                    "client_id": client_id,
                    "client_secret": client_secret,
                }, labels=app.get("secret_labels")),
                namespace,
                cert_file,
            )
            app_path.write_text(app_sealed)
            print(f"            → {app_path.relative_to(REPO_ROOT)}")

            # Seal for authentik namespace (env vars read by blueprint !Env)
            env_sealed = kubeseal(
                make_secret(f"{name}-oidc-env", "authentik", {
                    f"{prefix}_CLIENT_ID": client_id,
                    f"{prefix}_CLIENT_SECRET": client_secret,
                }),
                "authentik",
                cert_file,
            )
            env_path.write_text(env_sealed)
            print(f"            → {env_path.relative_to(REPO_ROOT)}")

            any_new = True
            new_secrets.append(f"{name}-oidc-env")

        # Regenerate blueprint (always — non-credential fields may have changed)
        BLUEPRINTS_DIR.mkdir(parents=True, exist_ok=True)
        blueprint_path = BLUEPRINTS_DIR / "oauth2-apps.yaml"
        blueprint_path.write_text(generate_blueprint(apps))
        print(f"[blueprint] {blueprint_path.relative_to(REPO_ROOT)}")

        # Regenerate Helm envFrom overlay (always)
        OIDC_ENV_VALUES.write_text(generate_oidc_env_values(apps))
        print(f"[values]    {OIDC_ENV_VALUES.relative_to(REPO_ROOT)}")

        # Generate per-app Helm OIDC overlays + patch cluster Application YAMLs (always)
        for app in apps:
            generate_app_oidc_values(app)
            patch_cluster_application(app)

    finally:
        os.unlink(cert_file)

    # Write list of newly-created secret names for the CI wait step.
    # Only secrets written this run need to be polled for unseal.
    new_secrets_file = REPO_ROOT / ".new-secrets"
    if any_new:
        new_secrets_file.write_text("\n".join(new_secrets) + "\n")
    else:
        new_secrets_file.unlink(missing_ok=True)

    # Exit code 2 signals to CI that new credentials were provisioned and
    # Authentik must re-apply the blueprint (via API call in the workflow).
    # Exit code 0 means no new credentials — blueprint re-apply not needed.
    sys.exit(2 if any_new else 0)


if __name__ == "__main__":
    main()
