---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgDiQd1odQXWfvSspdwVJhe6fXrq7oNdruAOBn/E63CdAgyuUP744RcBEKLMzIKwDnjJwOvKJHXZaYmuavaRU5TdgHB1ummNRUZlVKBXTX8kYF0bY/jmJS4PYY8vge8uqjAmT2XAwB62CA07dV4z7aoy0Gj0F8Xu9IVLCU47Qz+/NXpwAntRAFfbursnGGaq5liQnl5ousQAp8E5NlL9T5q953baUvI7hGNj9I8q13D36ghG73dZFfgSMXu+/Twr55TPENwer0dUcPzMKgp//lA+LfgVihzP/VLOXbQGY21tyRbcFzav1b85bElrHUqpVRVnFNHV0I085s4QvXYO/kLUmk8ChCBI9PVzCB5adw1fr4/x0D0PMps4kLshkDGqa3qBCzReWYql3zavj9kQ0+IyeKJ21fceBjzg6gJDUElkBWjIWlmmD/cl8HjDCfuolc9Z9dwzuXpLlnNh4rKtsTB2yztiQtw63nciA4MB2ZnMQRXJnBb2eNlfA+UAgZqIfnilaPNPMK5dNyHQvtAgL+6vSbcA1UG5Zrp4tLNL0SO9AR3j0RqbPLKHXRXeaOrRaEnnrfPiL35w2PjKKLhh+DZ5Roxt8snRQctEJBXNdSkKD3co2yI/XP//aFqstRlgYMVrA+t5iWQYtzC3CTyxH/UF9pTGl0fqhd5AnES2Dukc2pTEjED6UYjy+87nnSoyfEIpOMCWfUcm9MsL1SLilu63TqmL3bexhFcjsdf605Ycv+UDx9npsl0F1hT35iej+MuFvIF9e0CQTdvxjNMWh+9dMEcLvNTOlnrmIrZmAA2RBwJEcEpIF6BrFHmfdZngYDvSRccWDbeHHvywOAY3i+649bLrbtOmqEz2Xxjc3rdSilV4SUgWTKEM90FYKTHM3xKKL3c=
  template:
    metadata:
      creationTimestamp: null
      name: velero-r2-credentials
      namespace: velero
