apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.llama.storageClass }}
  resources:
    requests:
      storage: {{ .Values.llama.storage }}
