---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-secret
  namespace: ai
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgBn/eXO9a7aylXz1OzCR746EbSdmsWkx7QH28QfxbHssw11UEtjB8ZosGFdUKsd9vxIZQRnX44+gP27TJ7+TSdMbEXJqT61tT1t1DBGQJUXhr6igjqwR2XkSQLAK7q8AG25r/Usyk2ON+N0mtAcjZxIw2YOiuPrS6d5BncLok5j462dy3iyEmuXDvMTMjQxJ2RmshzQQIYRB2W9hhPI2q+BnlFO3qHmEtT7SJWqLAPbh3uKAop3S0SPkq3QNmo0QbR5W6/0Z3PDYZbGTcGD3foUPTvu4TRV82MtpfbVr1DuvuV/TZXEtyaui2lo2FNem/WkD3CFgUG/m/M9JOvxmufWBTXAfxmRv617IJyIwoKGTi+XqtMVWyc71coAS6x0xHhHmOvY+hYSEa8hQcgnKxAzyDn+fY/iyn2DpiLW8EStC1f9xp1sVvDjzozOXpKDzU02qFdUQTYAggJ1fhmy3FBcxiO5hKc84maJdtc6kCJZ+/qy96lunwGUJIG1/YecXwXQg4NveeH/mD7eSQUBmnRqnflfJrhEbLWXNAkMmXbB7CulEtoKtWTZcbZJ++6Gdi2yK7v/aDBI5xAd/DOAIuter0PNuOZIp+x4X/XFuVXcLegHJavPUy6iHfInN9e3j4vr7uSu0XcWljUvqfsm3WimWzT89XyedBLj+t81GPyRyb1rPGd3fL1E8sQuoJuClW4jCje+KtcFRe329nBM17iTpVJTdFGI/Q6zgIPXXFZjvcertZ402x2prsfQ76yq35UXRfvjQahLCDVM4VT3FPSj
  template:
    metadata:
      creationTimestamp: null
      name: open-webui-secret
      namespace: ai
