---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-oidc
  namespace: ai
spec:
  encryptedData:
    client_id: AgCiiieMQXHZ+v/Wwv2wG+2yIXSNzdKlMSN+mp//ocBCE4Xpdgw1S96Zb9xUjMR8tq5EHYX1Ae8CFDqWoLEs1PdRv306cU3kvrB3RKAX3xw1wNq1ORl+gtkrwIAeGwEZG2++I772MR/xvOFGRoUgv1a0phxrxFTiSX8j2B+ipGFRGO/vC5nkRipdlKr9nz7i1Ppz4jv0/z9nuTjJb43vUVczTnY+LEyA1YviTOrP+zTctrlrGMkQqqJhN+jPu2CtAcANjTVYlZ8l1aTf9yNIjOdLApqZWp9F0fl3210iHFvogNOzlu/BiB94r6HyAZ43ZjpR/Xg4gf7IfaejQG+cKl2Zv2qv0B78P6HEmp8orG5W6v39CUfhcjWZDfms6Ecl0dDRLKJiigWgEO7TFobL+fcxB2kgZT5Z6LORT4JWoxrjJMJ/PWhzLuxou1zjT/RLJDc2LKUL6jg2rTwdYva9mXksYKXJbDo+gqDtkf3xtOmwQIjgdkzxfSGh04kJ5Jd7lyOSoqMT+pirpL8KslzYv9ccaPr3gqRNHO9Tsx+Yekp+9N6Gsl0wrP+SBr/Jp9XpTqKJu1W9NSORuNbuOuDdHLWIxYN7lZaJeUziubQ/oZQpl73asGI+PvEhTcT8x8Gwab0hfAlCdUEoz0BW8Cg7SLGhhjBTMUtSaFtswx+TQn7PSp8eGFH6lTP+XESTHS56YxoneDCj7NULUW84s0VrSvkLUpHjIRi1pLQV6ndT8e9eqavbjJo=
    client_secret: AgC4qLZ8ijgvNmt6DjPPotwJshzWwPEZHAjTGfUiV46koCoLEO5bUO4rh78vQiPb0BWSu4QNlMNEKxrAkjKSyfXlOQqVllqPl0gzqH0Zt2a6OW1U+wIRtFEqGYKhrM5jy1maQ49rUDC6LA63zzugtB/vgzVyCDnOnffijVTGgXRaOWwIkBd4GXFv5K9Bf1aGNwKgjYsV4RyqwhMCuz4MB9b4RIpSzCzXk1hUOwMVStH/wB+VD2DhpxKDOJTuqDZ+lLEcTQK1mygNvGK/49uQ2FD7xPKKS9g3DZ4x7baDh4BZqkS12ybSf8NzSq51/XnVBeOkhpIL8Gj/uGNsXbhBTeEKyU0KNJL8fwizvro43r/esQOaEeMyE3eTyNkx3q50y0AFXxgfkZicVQyJkyrybdXUlQHqQFFYNyMwSSZgqoWLon8v6BE1cgA262mxY4k9HOmVdHL5Wvi4Wu0kMfJJuaJYhbOprrbSVb9aOl+qXNTeUmNLe5oV2nZQkWURs4aO+C7+ewEbNQVrsjhG3dBHudbcE8NyGmUesI8rVvCrS50ag7Jgrsz1u3AvVwq0js+dJib8bBUKgnznRAdbZVNClSkwhrTU9BoB+8thSO8tTB/HHDgoeTwMHOUheZGucSfLZg2hS2Aw+/KqO8UUaE1SKWi0ZkC7fk9cvqzBGola3oPTF1zSMGgfZ9hLe1kUuWDTj0fsvJwPcLMD51V8KfKOOnY/qSuaFR6j4yLbFW+zPiJGuH26I1yMwdAexaaSESmFpSS4Nnegk7RwveHT5AHkfplP6l6Glfj98de3H0smRseYftF8kfN6U3ey7C7fotmZbLGywq1rN3RtBykPz5UjqIHeTjFNtWA9ysYxTMjJ5Z+c3w==
  template:
    metadata:
      creationTimestamp: null
      name: open-webui-oidc
      namespace: ai
    type: Opaque
