---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secret
  namespace: ai
spec:
  encryptedData:
    SEARXNG_SECRET: AgAQ3xydRY1yKOX5D94LFJIhqPA7O2RpFWUSKZgrit8APH9Aaqk217HZPuFBdVSUBqaxGzEwm+g+mku5PkXtazyWmG5/sUKJZsEitSJz5mlPKjF4gBQ0dB8vgnnBc3X0HwhPShxseX0hTcSj2PkgKsmzhkz5esyffEGUh6G1mNYFhj9NCd9fARSy8NG5IHdIu4EafyrIXwtLs73Ys2ibsn93qKnnfO1qGKfN7/7rPte4UT60+vDNYAgHvigVlx8aMDuez9gcPEjgpxa7f9P8rg/C2LorFE2RXW8NolOS7kfiJAVgWnSKIgS5OQ1x+HXslGkmwizB4goOpQv8In6SolHaJINzLb1g6IwOtyDkn4hPZ8JL0PZ7aa0lbjkVrOFy15WlpLNmowffpmq79IykHP9o+TpZRrXba2FTzObhgxW3chzwxeO2NRv7YSdW1mdlGh3C9hzbZbHvLaXGLuF3TYlYh5tKYkHoonH9IiL8RAwBaLsgKXUAPzBLeZ5rbcc6pQR+r520pfxTC/2pLOotxEeFyRvlN9ksBvtT/HetDnKZIiMLkC67YwW0VER6nZKCmtHPHaDzOk6DZC0W2SjH3r7CzwlG7ff2wVVYTu6kJs/19gww+2sqrtFYmkrrQezJ2aNuB5zkkhi7t0BTEaKwukRDw757RPD0OmkpyebGFst/lgak3UIfQlxw2KVpKk1E5XBJE+9UrGxB9bsNmX0LUMMGsaMGuHX3tzV8JgP6tL4vqVAeQyzxPr5xlIPO8pUKuC8rD2c5AXzfPFU8Yqb8Ky4B
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secret
      namespace: ai
